Blog/App/urls.py
from django.conf.urls import url
from App import views


urlpatterns = [
    url(r'^index/(\d+)',views.index,name='index'),
    url(r'^register/',views.register,name='register'),
    url(r'^doregister/',views.do_register,name='doregister'),
    url(r'^login/',views.login,name='login'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^sendposts/',views.sendposts,name='sendposts'),
    url(r'^detail/(\d+)/',views.detail,name='detail'),
    url(r'^cpost/(\d+)/',views.cposts,name='cposts'),
    url(r'^search/',views.search,name='search'),
    url(r'^registhandler/',views.register_handler,name='registhandler'),
    url(r'^loginhandler/',views.login_handler,name='loginhandler'),
    url(r'^useractivate/(.*?)/',views.user_activate,name='useractivate'),
    url(r'^collect/(\d+)/',views.coll_post,name='collect'),
    url(r'^mycoll',views.mycoll,name='mycoll'),

]

Blog/Blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('App.urls',namespace='blog'))
]

Blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <script src="{% static 'js/jquery.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block resource %}

    {% endblock %}
</head>
<body>
{% block content %}
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand active" href="#">CatoryBlog</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'blog:sendposts' %}">发帖 <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">我的帖子</a></li>
                    <li><a href="{% url 'blog:mycoll' %}">我的收藏</a></li>

                </ul>
                <form method="post" class="navbar-form navbar-left" action="{% url 'blog:search' %}">
{#                    <div class="form-group">#}
                    {% csrf_token %}
                        <input type="text" name="search" placeholder="请输入查找内容">
{#                    </div>#}
{#                    <a href="{% url 'blog:search' %}" type="submit" class="btn btn-default">搜索</a>#}
                    <input type="submit" value="搜索">
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.session.user %}

                        <li><a href="{% url 'blog:logout' %}">退出</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">{{ request.session.user }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">个人中心</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">修改密码</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">修改邮箱</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">上传头像</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'blog:login' %}">登录</a></li>
                        <li><a href="{% url 'blog:register' %}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    {% block page_content %}

    {% endblock %}
{% endblock %}

</body>
</html>

Blog/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block resource %}
    <style>
        .content {
            width: 60%;
            height: 100px;
            margin: 30px auto;
        }

        .butt {
            width: 50px;
            height: 25px;
            background: deepskyblue;
        }
        .comment{
            width:50%;
            height: 50px;
            margin-left:50px ;
        }
    .post{
        width:50%;
        height:120px;
    }
    .time{
        float: right;
    }
    .collect{
        float: right;
    }
    .glyphicon glyphicon-heart{
        color: red;
        background: red;
    }
    </style>
    <script src="{% static 'js/detail.js' %}"></script>
{% endblock %}
{% block page_content %}
    <input type="hidden" id="postid" value={{ post.id }}>
    <div class="panel panel-default post">
        <div class="panel-heading">
            <h3 class="panel-title">{{ post.ptitle }} --->浏览量{{ count }}<span class="collect">收藏</span></h3>
        </div>
        <div class="panel-body">
            {{ post.pcontent }}
            <div class="time">{{ post.ptime }}</div>
        </div>
    </div>

    {% if reposts %}
        <h3>全部评论</h3>

        {% for repost in reposts %}
            <div class="panel panel-default comment">
                <div class="panel-body">
                    <span>{{ repost.puser.username }}说：</span>
                    {{ repost.pcontent }}
                    <div class="time">{{ post.ptime }}</div>
                </div>

            </div>
        {% endfor %}
    {% endif %}
    <br>
    <h3>我也说两句</h3>

    <form method="post" action="{% url 'blog:cposts' post.id %}">
        {% csrf_token %}
        <textarea class="content" type="text" name="content" placeholder="说出我的心声"></textarea><br>
        <input class="butt" type="submit" value="评论">
    </form>
{% endblock %}

Blog/templates/index.html
{% extends 'base.html' %}

{% block resource %}
    <style>
        .post {
            width: 50%;
            height: 120px;
        }

        .time {
            float: right;
        }
    .rank{
        position: absolute;
        left: 60%;
        top: 10%;
        width: 25%;
    }
    .hotpost{
        position: absolute;
        left: 60%;
        top: 50%;
        width: 25%;
    }
    .count{
        float: right;
    }
    .comment{
        float: right;
        font-size: 12px;
    }
    </style>
{% endblock %}

{% block page_content %}
    <h3>welcome to my blog</h3>
    {% for post,count in comment_counts %}
        <div class="panel panel-default post">
            <div class="panel-heading">
                <h3 class="panel-title">{{ post.ptitle }}<span class="comment">{{ count }}条评论</span></h3>

            </div>
            <div class="panel-body">
                <a href="{% url 'blog:detail' post.id %}">{{ post.pcontent }}</a>
                <div class="time">{{ post.ptime }}</div>
            </div>
        </div>
    {% endfor %}

    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li>
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for page in pages %}
                <li><a href="{% url 'blog:index' forloop.counter %}">{{ forloop.counter }}</a></li>
            {% endfor %}
            <li>
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>

    <div class="rank">

        <div class="panel panel-primary">

            <div class="panel-heading">热门文章</div>

            <ul class="list-group">
                {% for post,count in rank %}

                    <li class="list-group-item"><a href="{% url 'blog:detail' post.id %}">{{ post.ptitle }} <span class="count">访问量{{ count }}</span> </a></li>

                {% endfor %}

            </ul>
        </div>

    </div>

    <div class="hotpost">

        <div class="panel panel-primary">

            <div class="panel-heading">热议帖子</div>

            <ul class="list-group">
                {% for post,count in post_five %}

                    <li class="list-group-item"><a href="{% url 'blog:detail' post.id %}">{{ post.ptitle }} <span class="count">评论数{{ count }}</span> </a></li>

                {% endfor %}

            </ul>
        </div>

    </div>
    <div>当前在线人数：{{ onlineuser }}</div>
{% endblock %}

Blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block resource %}
    <style>
        .regist{
            width: 50%;
            margin: 100px auto !important;
        }
        .login{
            width: 90%;
            height:35px;
            margin:10px 5% !important;
            border:1px solid grey;
            border-radius:3px ;
        }
    .butt{
        background: greenyellow;
    }
    </style>
    <script src="{% static 'js/login.js'%}"></script>
{% endblock %}
{% block page_content %}
    <div class="container">
        <div class="panel panel-primary regist">
            <div class="panel-heading">
                <h3 class="panel-title">登录</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="{% url 'blog:login' %}">
                    {% csrf_token %}
                    <input class="login" id="username" type="text" name="username" placeholder="请输入用户名"><br>
                    <input class="login" id="password" type="password" name="password" placeholder="请输入密码"><br>
                    <input class="butt login" type="submit" value="登录">
                </form>

            </div>
        </div>
    </div>
{% endblock %}

Blog/templates/mycollections.html
{% extends 'base.html' %}

{% block resource %}

{% endblock %}

{% block page_content %}

    <h3>love blog</h3>
    {% for post in posts %}
        <div class="panel panel-default post">
            <div class="panel-heading">
                <h3 class="panel-title">{{ post.ptitle }}</h3>
            </div>
            <div class="panel-body">
                <a href="{% url 'blog:detail' post.id %}">{{ post.pcontent }}</a>
                <div class="time">{{ post.ptime }}</div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

Blog/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block resource %}
    <style>
        .regist{
            width: 50%;
            margin: 100px auto !important;
        }
        .login{
            width: 87%;
            height:35px;
            margin:10px 5% !important;
            border:1px solid grey;
            border-radius:3px ;
        }
        .star{
            color: red;
        }
        .note{
            margin:5px 5% !important;
        }
    .butt{
        background: greenyellow;
    }
    </style>
    <script src="{% static 'js/register.js'%}"></script>
{% endblock %}
{% block page_content %}
    <div class="container">
        <div class="panel panel-primary regist">
            <div class="panel-heading">
                <h3 class="panel-title">注册</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="{% url 'blog:doregister' %}">
                    {% csrf_token %}
                    <input class="login" id="username" type="text" name="username" placeholder="请输入用户名"><span class="star">*</span><br>
                    <span class="note">注：20个字符以内，注意区分大小写</span>
                    <input class="login" id="email" type="text" name="email" placeholder="请输入邮箱"><span class="star">*</span><br>
                    <input class="login" id="pwd" type="password" name="password" placeholder="请输入密码"><span class="star">*</span><br>
                    <span class="note">注：密码必须至少包含8个字符，不能全部为数字</span>
                    <input class="login" id='cpwd' type="password" name="cpassword" placeholder="再次确认密码"><span class="star">*</span><br>
                    <input class="butt login" type="submit" value="注册">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Blog/templates/registr_jump.html
{% extends 'base.html' %}

{% block page_content %}
    <h3>激活成功</h3>
    <a href="{% url 'blog:index' 1 %}">点我,快去逛逛吧</a>
{% endblock %}

Blog/templates/search.html
{% extends 'base.html' %}

{% block page_content %}


    <div class="panel panel-default col-md-3">
        <div class="panel-heading">
            <h3 class="panel-title">{{ post.ptitle }}</h3>
        </div>
        <div class="panel-body">
            <a href="{% url 'blog:detail' post.id %}">{{ post.pcontent }}</a>
        </div>
    </div>


{% endblock %}

Blog/templates/sendposts.html
{% extends 'base.html' %}

{% block resource %}
    <style>
        .title{
            width: 40%;
            height: 50px;
            margin: 10px auto;
        }
        .content {
            width: 70%;
            height: 200px;
            margin: 30px auto;
        }

        .butt {
            width: 50px;
            height: 25px;
            background: deepskyblue;
        }
    </style>
{% endblock %}
{% block page_content %}
    <div class="container">
        <form method="post" action="{% url 'blog:sendposts' %}">
            {% csrf_token %}
            <textarea class="title" type="text" name="title" placeholder="标题"></textarea><br>
            <textarea class="content" type="text" name="content" placeholder="说点什么。。。"></textarea><br>
            <input class="butt" type="submit" value="发表">
        </form>
    </div>
{% endblock %}